### ISSUE TITLE
signup.php connect issue

### ISSUE THREAD

**Issue by albingcj** [sabhari-krr/five#6]
> Warning Undefined array key "profilepic" in C:\xampp\htdocs\five signup.php on line 6
> Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\ five signup php on line 6
> Warning: Undefined array key "profilepic" in C:\xampp\htdocs\ five signup.php on line 7
> Warning: Trying to access array offset on value of type null in C:\xampp\htdocs\ five signup.php on line 7

No issues while inserting with rerg.php. but throwing these errors when inserting profile pic with this code.

**Comment by sabhari-krr** [comment]
Will have a look at it tomorrow once I get access to any Windows machine
